### ISSUE TITLE
安装主题后无法启动qq

### ISSUE THREAD

**Issue by forchannot** [MUKAPP/BetterQQNT-MSpring-Theme#1]
![image](https://github.com/MUKAPP/BetterQQNT-MSpring-Theme/assets/100580891/111d17cf-f9b0-46bd-a6a3-079ad62431d3)
报错如上图，删掉插件后启动正常，测试了原版的test-theme也正常

**Comment by MUKAPP** [comment]
我更新了BetterQQNT之后也出现了，我研究研究

**Comment by MUKAPP** [comment]
已修复
