### ISSUE TITLE
奇怪的问题

### ISSUE THREAD

**Issue by Xcating** [MUKAPP/BetterQQNT-MSpring-Theme#10]
![image](https://github.com/MUKAPP/BetterQQNT-MSpring-Theme/assets/82816129/24572b65-0ac9-4f77-a1ad-dec2154eca12)
黑暗模式似乎不对劲
![image](https://github.com/MUKAPP/BetterQQNT-MSpring-Theme/assets/82816129/5bc58989-3051-4f76-a0d2-a05a8a9c5f29)
![image](https://github.com/MUKAPP/BetterQQNT-MSpring-Theme/assets/82816129/96c711ad-7fd2-44ab-b298-143a4849abbf)

**Comment by MUKAPP** [comment]
这个QQ好像不是最新版）




MUKAPP
***@***.***







                       
原始邮件
                       
                     

发件人："TeaTing"< ***@***.*** &gt;;

发件时间：2023/7/1 19:17

收件人："MUKAPP/BetterQQNT-MSpring-Theme"< ***@***.*** &gt;;

抄送人："Subscribed"< ***@***.*** &gt;;

主题：[MUKAPP/BetterQQNT-MSpring-Theme] 奇怪的问题 (Issue #10)




 

 黑暗模式似乎不对劲

**Comment by Xcating** [comment]
![Uploading image.png…]()

**Comment by MUKAPP** [comment]
最新14480，加了背景模糊
![image](https://github.com/MUKAPP/BetterQQNT-MSpring-Theme/assets/41848070/030054c5-9edb-469e-bb69-faab50fb720d)

**Comment by Xcating** [comment]
？链接发一下

**Comment by Xcating** [comment]
竟然没有提示这个的更新🥹

**Comment by MUKAPP** [comment]
Windows QQ 9.8.5版本修复了若干大家反馈的bug
【下载链接】
x64：https://dldir1.qq.com/qqfile/qq/QQNT/c413e6c5/QQ9.8.5.14480_x64.exe
【版本特性】
修复了若干已知bug

**Comment by Xcating** [comment]
谢谢大佬
