### ISSUE TITLE
查看聊天记录窗口未应用半透明效果

### ISSUE THREAD

**Issue by lemon-sundae** [MUKAPP/BetterQQNT-MSpring-Theme#100]
使用该主题插件给QQ主窗口设置透明度后，查看聊天记录的窗口依然是完全不透明，和主窗口摆在一起有点突兀，不太美观，不知道能不能优化一下

**Comment by MUKAPP** [comment]
配合 [More Materials](https://github.com/mo-jinran/More-Materials) 插件使用
