### ISSUE TITLE
[BUG] 3.2.12-27187 列表项圆角失效

### ISSUE THREAD

**Issue by TTsdzb** [MUKAPP/BetterQQNT-MSpring-Theme#101]
LiteLoader: 1.2.1
QQNT: 3.2.12-27187
Electron: 31.0.1
Chromium: 126.0.6478.36
NodeJS: 20.14.0
MSpring Theme: 1.3.4

效果如图，margin 貌似是正常的，只是圆角没了：

![image](https://github.com/user-attachments/assets/20c9d222-71db-4c6d-ab5e-8c34c8566222)

预期行为：

像原先一样有圆角。

**Comment by efojug** [comment]
9.9.15-27333可复现

**Comment by nikoyoke1** [comment]
9.9.15-27254复现
