### ISSUE TITLE
新UI

### ISSUE THREAD

**Issue by YatFanLan** [MUKAPP/BetterQQNT-MSpring-Theme#103]
希望可以把联系人界面的点击选中联系人之后的选中界面修改为 和MSpring-Theme 主题部分一致的样子  加入这个插件之后 其他界面都挺圆润，只有在选中联系人之后选项框感觉特别生硬

**Comment by YatFanLan** [comment]
我是用CSS修改点击选中联系人之后的界面样式之后，展示效果和MSpring-Theme 主题部分一致
 /*让联系人列表界面选择之后展示为圆角*/
.list-item {
    border-radius: 8px; /* 设置你希望的圆角大小 */
}
这是CSS代码 希望能够有帮助

**Comment by YatFanLan** [comment]
在该插件文件夹的src目录下的style.css中加入
.list-item {
border-radius: 8px; /* 设置你希望的圆角大小 */
}
这段代码即可

**Comment by YatFanLan** [comment]
在插件根目录下的src下的style.css 文件内加入
/*让联系人列表界面选择之后展示为圆角*/
.list-item {
border-radius: 8px; 
}
即可达到效果

**Comment by MUKAPP** [comment]
已修复，感谢
