### ISSUE TITLE
如何在不使用该项目的情况下修改主题色

### ISSUE THREAD

**Issue by YCZ01111** [MUKAPP/BetterQQNT-MSpring-Theme#104]
我尝试使用css来控制消息列表中被选中的卡片的颜色，但是发现该颜色必须通过修改主题色来更改，您是以什么方式修改主题色的？原谅我学习甚浅没有看懂您的源码。求指教

**Comment by MUKAPP** [comment]
![image](https://github.com/user-attachments/assets/805d60f0-7f60-4c15-96ba-63bb3c338a5c)
这个是主题色

**Comment by YCZ01111** [comment]
> ![image](https://private-user-images.githubusercontent.com/41848070/365436673-805d60f0-7f60-4c15-96ba-63bb3c338a5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTg1NjAsIm5iZiI6MTcyNTc5ODI2MCwicGF0aCI6Ii80MTg0ODA3MC8zNjU0MzY2NzMtODA1ZDYwZjAtN2Y2MC00YzE1LTk2YmEtNjNiYjNjMzM4YTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDEyMjQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZDQ3OTAzNjZlM2Q2ZTRhNWM2YjM2NzcxMWFmYzdjNjhjNmMxYjg1Y2IzNjYzNTcxOTFiYjI1OTVmZTI4OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fyZAzihHxhsleYgFDbAtP1NVvr6b93h7qNlSIkfRRBk)这个是主题色

万分感谢
