### ISSUE TITLE
安装主题后遮挡最后一条消息

### ISSUE THREAD

**Issue by fatinghenji** [MUKAPP/BetterQQNT-MSpring-Theme#2]
![579ae18839e3e16b0008498aab63e327](https://github.com/MUKAPP/BetterQQNT-MSpring-Theme/assets/37131177/86c583a9-17ad-436e-bd30-d780ae86646e)

**Comment by fatinghenji** [comment]
笨比问题，手动调整聊天框高度解决。

**Comment by MUKAPP** [comment]
确实是有这个问题，目前已知第一次安装主题后会出现，调整窗口大小（包括最大化）之后也会出现
暂时不知道什么原因引起，也无法修复（）
目前的解决办法就是往下拖动一下聊天框顶端

**Comment by huankong233** [comment]
![image](https://github.com/MUKAPP/BetterQQNT-MSpring-Theme/assets/49610758/31b2670d-59c0-4824-a733-f2a3f5ee4f26)

**Comment by MUKAPP** [comment]
> ![image](https://user-images.githubusercontent.com/49610758/245383435-31b2670d-59c0-4824-a733-f2a3f5ee4f26.png)

之前研究了一下这里，但是不知道为什么会变（）

**Comment by fatinghenji** [comment]
问题似乎依旧存在

**Comment by MUKAPP** [comment]
> 问题似乎依旧存在

最新版QQ的话应该只是在第一次安装主题会遮挡，拖着输入框的上边框往下拽一下就好了（）
调整窗口大小什么的也不会变
