### ISSUE TITLE
[功能增强]支持类似telegram主题的连续聊天合并

### ISSUE THREAD

**Issue by KagaJiankui** [MUKAPP/BetterQQNT-MSpring-Theme#29]
能否实现类似隔壁telegram主题的连续聊天合并、隐藏连续头像、隐藏连续用户名功能？

**Comment by MUKAPP** [comment]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/1ecfd6ce-2ef0-4216-878b-7d5aecc1f880)
这种怎么样

**Comment by MUKAPP** [comment]
有时候会有点问题，但是搞不明白为什么（）
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/140448f1-a1f5-4a01-8f04-27dca894959d)

**Comment by KagaJiankui** [comment]
> ![image](https://user-images.githubusercontent.com/41848070/257541537-1ecfd6ce-2ef0-4216-878b-7d5aecc1f880.png) 这种怎么样

可以把头像放到最后一条消息的位置，我完全不懂前端开发（）

**Comment by MUKAPP** [comment]
> 可以把头像放到最后一条消息的位置，我完全不懂前端开发（）

事实上我也不怎么懂前端开发（）
我之前试了把头像放到最下面，但是有的消息生效有的消息不生效，搞不明白就放最上面了
