### ISSUE TITLE
聊天记录上方搜索栏圆角有问题

### ISSUE THREAD

**Issue by huankong233** [MUKAPP/BetterQQNT-MSpring-Theme#3]
聊天记录上方搜索栏圆角有问题
![image](https://github.com/MUKAPP/BetterQQNT-MSpring-Theme/assets/49610758/7ac75f02-5895-4a5c-94e2-b84fc0980f46)

**Comment by MUKAPP** [comment]
很奇怪，我从昨天就开始找搜索框的边框是在哪里设置的，但是一直找不到
![image](https://github.com/MUKAPP/BetterQQNT-MSpring-Theme/assets/41848070/b8aab3c2-0d9e-491a-82ce-73e72b06a307)
而且border-radius对这个边框也不起作用

下面消息背景已经修好了

**Comment by huankong233** [comment]
> 很奇怪，我从昨天就开始找搜索框的边框是在哪里设置的，但是一直找不到 ![image](https://user-images.githubusercontent.com/41848070/245391120-b8aab3c2-0d9e-491a-82ce-73e72b06a307.png) 而且border-radius对这个边框也不起作用
> 
> 下面消息背景已经修好了

我也没找到，怪了吧唧的

**Comment by huankong233** [comment]
> 很奇怪，我从昨天就开始找搜索框的边框是在哪里设置的，但是一直找不到 ![image](https://user-images.githubusercontent.com/41848070/245391120-b8aab3c2-0d9e-491a-82ce-73e72b06a307.png) 而且border-radius对这个边框也不起作用
> 
> 下面消息背景已经修好了

找到了
~~~css
.record-search .search .search-input{
  border-radius: 4px !important;
}
~~~

**Comment by huankong233** [comment]
> > 很奇怪，我从昨天就开始找搜索框的边框是在哪里设置的，但是一直找不到 ![image](https://user-images.githubusercontent.com/41848070/245391120-b8aab3c2-0d9e-491a-82ce-73e72b06a307.png) 而且border-radius对这个边框也不起作用
> > 下面消息背景已经修好了
> 
> 找到了
> 
> ```css
> .record-search .search .search-input{
>   border-radius: 4px !important;
> }
> ```

![image](https://github.com/MUKAPP/BetterQQNT-MSpring-Theme/assets/49610758/b431d0bc-e3be-4de7-94e7-c0f173a32926)
