### ISSUE TITLE
1.0.7版本设置界面消失

### ISSUE THREAD

**Issue by imyifeng** [MUKAPP/BetterQQNT-MSpring-Theme#31]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/70053196/3a5f9ccc-47f9-4be1-9f7a-a04033a2c361)
如图

**Comment by MUKAPP** [comment]
请更新至0.5.0版本liteloader（release被作者撤包了，可以clone仓库）或者回退1.0.5版本主题
