### ISSUE TITLE
回复文字颜色调整

### ISSUE THREAD

**Issue by KagaJiankui** [MUKAPP/BetterQQNT-MSpring-Theme#33]
回复文字颜色、亮色主题下文字颜色的色差较低，调整主题颜色无法得到很好的区分度，回复文字不太清晰
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/58453886/9a818d53-9dae-48c4-a43c-a41cf7207fec)

![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/58453886/4b766c29-1fd1-496e-a338-aad1e8cb9129)

**Comment by MUKAPP** [comment]
看样子是背景插件修改了文字颜色
他css里好像用了important，我试试能不能盖过他

**Comment by MUKAPP** [comment]
已解决，请更新至1.1.2版本
