### ISSUE TITLE
希望可以优化res文件夹

### ISSUE THREAD

**Issue by qiuyue0** [MUKAPP/BetterQQNT-MSpring-Theme#34]
使用插件市场下载时会将res文件夹一并下载，希望可以将res文件夹中的图片放在其他地方，Readme.md的图片使用链接引用

**Comment by MUKAPP** [comment]
插件市场下的是release啊，怎么会有res文件夹呢

**Comment by MUKAPP** [comment]
我release里去掉res了

**Comment by qiuyue0** [comment]
> 我release里去掉res了

看了一下，应该是旧版的问题，我想更新半天更新不下载，看到旧版的manifest.json还是写的branch main，哈哈
