### ISSUE TITLE
`请用手机 QQ 允许登录`字体颜色未适配

### ISSUE THREAD

**Issue by wenxuanjun** [MUKAPP/BetterQQNT-MSpring-Theme#35]
## 问题描述

在深色模式下，`请用手机 QQ 允许登录`仍然为黑色。

## 效果

![图片](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41050170/dce76fb7-9726-474b-a30d-78ec47b2ed0c)

## 相关 CSS

```
.status .notice>span[data-v-584fb35c] {
    color: rgba(0,0,0,.72);
    font-size: 16px;
    font-weight: 500;
}
```

**Comment by MUKAPP** [comment]
我这里是 `.auto-login .status-txt` 你的操作系统以及QQ版本是什么呢

**Comment by wenxuanjun** [comment]
抱歉忘记提供相关信息。

```
OS: Linux
QQNT: 3.1.2-13107
LiteLoader: 0.5.0
```

**Comment by wenxuanjun** [comment]
注意到在 https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/commit/98d043526214cafb7f5036601299424f9ed3c0c1 中已修复，谢谢。
