### ISSUE TITLE
开启优化消息排版后导致 链接/@ 渲染出错

### ISSUE THREAD

**Issue by GoForceX** [MUKAPP/BetterQQNT-MSpring-Theme#37]
如题

优化消息排版开启时，对于同时含有 @消息/链接 与 文字的消息中，会导致产生大量空格

# 环境

QQ: v9.9.1-15820
LiteLoader: v0.5.0 (Commit ac0799b9)
MSpring: v1.1.2

# 效果

![74685407916e8ad0bd0d51435e9380ad](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/67143590/1078d8fb-844c-49bb-af87-f815731e5a6c)

![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/67143590/5e9569a8-b02b-4027-a084-b1eb159037e9)

# Devtools

在含有 @ 的消息中，同时含有多个 class=text-element 的 span，
在只有 2 个 text-element 的情况下，两个 span 被分别添加了 6 个 heti-spacing 元素。

![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/67143590/26647856-516d-4fa9-a92e-d5cd2b93d782)

**Comment by MUKAPP** [comment]
赫蹏的脚本在@与中文之间默认加了空格
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/ebd0db0c-9ff2-4711-9914-967335fff3ce)
我是直接引入了赫蹏的原始脚本，并未对其进行修改

**Comment by MUKAPP** [comment]
如果想优化的话我可以试试修改赫蹏的js

**Comment by GoForceX** [comment]
可能是我这环境的问题？

刚才又进行了一波测试，貌似触发条件可能有些极端？而且不同条件下触发出的 heti-spacing 数量有所不同

![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/67143590/68ae0798-c2dd-42d9-b269-6d5fcb3b4faa)

**Comment by MUKAPP** [comment]
没太理解你的意思（）
你的理想情况是什么样的

**Comment by GoForceX** [comment]
理想情况是中间没有这一堆空格

**Comment by MUKAPP** [comment]
![f497b1e9eff96a02d17ada6d2fa7fbfc](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/efc8ffaa-1713-4bab-afe0-042b4cce8f07)
这中间的空格是你手动打的吗

**Comment by GoForceX** [comment]
并不是，是 heti 生成的 heti-spacing 元素导致的，具体的在 DOM 树截图中有

**Comment by GoForceX** [comment]
跟@这个字符并没有什么关系
个人认为是 qq 会把 @xxx 包在 text-element--at 中导致的，并不是消息中这些字符本身导致的问题，但是也不太确定的（）

关闭优化消息排版后，这两条消息中的大量空格就消失了：
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/67143590/be4ff27f-5b01-4e24-814f-43c945636582)

**Comment by GoForceX** [comment]
刚才偶然发现貌似和@没有什么关系（）

![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/67143590/57e25f53-1c29-4b83-a839-0cf884e67948)

图片中第一条消息中的冒号是中文全角冒号"："，而第二条中是英文半角冒号":"

~~现在马上去改一下 issue 标题~~

**Comment by MUKAPP** [comment]
我大概知道原因了，我先改改试试

**Comment by GoForceX** [comment]
非常感谢（手动磕头

**Comment by MUKAPP** [comment]
https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/commit/9ebdc67005cb77ca0e6a55b2a74dc8ce74d6ac14 已修复

**Comment by GoForceX** [comment]
我这边已经没有问题了，感谢！
