### ISSUE TITLE
能否增加登录页面背景自定义？

### ISSUE THREAD

**Issue by ayakasuki** [MUKAPP/BetterQQNT-MSpring-Theme#38]
登录页面白色有点小怪 之前改css的.login-container是可以的 现在不晓得为啥不行

**Comment by MUKAPP** [comment]
我觉得还行啊，反正每天也就看到一次（）
你试试改 `.login-container` 的css

**Comment by ayakasuki** [comment]
> 我觉得还行啊，反正每天也就看到一次（） 你试试改 `.login-container` 的css

改过了 （）三个都改了 好像还是没起效

**Comment by MUKAPP** [comment]
你什么系统，是mac吗

**Comment by ayakasuki** [comment]
> 你什么系统，是mac吗

win11来着

**Comment by ayakasuki** [comment]
> 你什么系统，是mac吗

是改style.css没错嘛

**Comment by MUKAPP** [comment]
那你的QQ版本呢

**Comment by MUKAPP** [comment]
> 是改style.css没错嘛

是的

**Comment by ayakasuki** [comment]
> 那你的QQ版本呢

15820 怪了 我挂图床的图片可以 本地的不可以 可能我没设置对 可能是我自己问题（怪不好意思的）

**Comment by ayakasuki** [comment]
不行 本地我试了/或\都不可以，但是url用https的图床就可以
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/20859971/04124563-aea2-426a-b42e-5300d997ea14)

**Comment by MUKAPP** [comment]
试试本地路径前面加上 `llqqnt://local-file/`

**Comment by ayakasuki** [comment]
> 试试本地路径前面加上 `llqqnt://local-file/`

好 我试试

**Comment by ayakasuki** [comment]
> > 试试本地路径前面加上 `llqqnt://local-file/`
> 
> 好 我试试

这个可以了！
