### ISSUE TITLE
透明表情被错误的添加了背景颜色

### ISSUE THREAD

**Issue by GoForceX** [MUKAPP/BetterQQNT-MSpring-Theme#39]
环境
QQ: v9.9.1-15820
LiteLoader: v0.5.0 (Commit ac0799b9)
MSpring: v1.1.3

# 效果
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/67143590/c587c96e-3c07-4196-b809-264eb29b2c05)

**Comment by MUKAPP** [comment]
嗯？
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/43ffa3c1-bc8c-41ca-98dd-9818aeefb579)

**Comment by GoForceX** [comment]
今早重启了一下电脑竟然好了……

这玩意怎么时断时续的……一会好一会坏，不知道怎么回事。

如果还有遇到同样问题的人可以试着 Reopen 一下（

**Comment by EnderturtleOrz** [comment]
我遇到了问题，我这里似乎所有别人发的消息都被染上了气泡的颜色，但是自己的没有问题，我不知道是不是我哪里配置错了
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/45251727/9c878cb9-c9cd-418a-8c7d-759898ae59dc)
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/45251727/b0ba5bd4-fdd7-4896-b245-3937954c1680)
