### ISSUE TITLE
win10怎么开启毛玻璃效果呢

### ISSUE THREAD

**Issue by Sunsh4j** [MUKAPP/BetterQQNT-MSpring-Theme#41]

**Comment by MUKAPP** [comment]
win10没有官方的开启方法
可以试试 https://github.com/MicaForEveryone/MicaForEveryone 这种软件，单独开QQ的（我没试过）

**Comment by Sunsh4j** [comment]
> win10 没有官方的开启方法 可以试试 https://github.com/MicaForEveryone/MicaForEveryone 这种软件，单独开 QQ 的（我没试过）

哦哦，好的。
