### ISSUE TITLE
不该透明的地方透明了()

### ISSUE THREAD

**Issue by HotspringDev** [MUKAPP/BetterQQNT-MSpring-Theme#42]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/78401087/4f48d53b-8b28-4a65-af2b-266502cab653)
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/78401087/e092122c-4b3f-4028-a0fd-4e44e9d9f9be)
OS:Linux,QQ3.1.2 (13107)
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/78401087/4a7744e7-c721-402d-8f26-92a2c74f737e)
设置里是不透明的

**Comment by MUKAPP** [comment]
我暂时没有linux环境，之后改（）

**Comment by MUKAPP** [comment]
已修复（）
