### ISSUE TITLE
优化消息排版和连续消息合并未生效

### ISSUE THREAD

**Issue by RubyFox31** [MUKAPP/BetterQQNT-MSpring-Theme#43]
QQ 9.9.1-15717
LiteLoader 通过 clone 安装

主题开启优化消息排版和连续消息合并通过 devtools 查看已开启，但 QQ 界面没有变化

![devtools](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/31060131/de16452d-73c0-41dd-8bc0-21c44a55fbfe)
![2](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/31060131/f63bd03d-45ed-48ee-ab87-47620a119a5d)
[log.txt](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/files/12368212/log.txt)
[settings.txt](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/files/12368215/settings.txt)

**Comment by RubyFox31** [comment]
Markdown-it 已关闭

**Comment by MUKAPP** [comment]
你还装了什么插件吗

**Comment by RubyFox31** [comment]
其中 Chii DevTools、Markdown-it 为关闭

![3](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/31060131/cd2a0997-78f9-4ad4-8103-3eb6b096d4ca)
另外，我又重启了几次，又可以正常生效。
生效时的 devtools

![devtools-2](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/31060131/bc47a48d-e3b1-45e4-9207-4293000ce501)

**Comment by MUKAPP** [comment]
最新版已修复 https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/releases/tag/v1.1.5
