### ISSUE TITLE
设置界面透明的问题

### ISSUE THREAD

**Issue by ACbye** [MUKAPP/BetterQQNT-MSpring-Theme#44]
版本: 9.9.2-15962 
系统: Win10 22H2
透明度开启过高会导致背景插件失效
透明度开启过低会导致设置界面异常亮

![Quicker_20230831_154750](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/56549504/8a677338-e3da-4710-9600-b4d842bfed2f)

**Comment by MUKAPP** [comment]
win10的qq没有窗口透明，请将透明度调到最高

**Comment by ACbye** [comment]
调到最高的话，背景插件就无法正常显示图片了，有什么解决办法吗

**Comment by MUKAPP** [comment]
我这里现在测试关闭透明效果之后，无论背景颜色透明度如何调整，设置界面都不会受影响了
