### ISSUE TITLE
特定颜色下，链接颜色看不见

### ISSUE THREAD

**Issue by ayakasuki** [MUKAPP/BetterQQNT-MSpring-Theme#45]
例如蓝色，链接也是蓝色，能不能考虑如果接近链接色，则自动变白色加下划线呢？

**Comment by MUKAPP** [comment]
截图看看？自己发的链接默认是白色的

**Comment by ayakasuki** [comment]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/20859971/fff60c6c-2bf8-48e8-b90a-27d0c7bab508)

**Comment by MUKAPP** [comment]
建议单独开一下主题看看是不是还是这种情况
