### ISSUE TITLE
消息合并功能与其他插件冲突

### ISSUE THREAD

**Issue by xyls184** [MUKAPP/BetterQQNT-MSpring-Theme#48]
[轻量工具箱](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools/)和MSpring theme(即本项目)都实现类tg消息合并，但是在轻量工具箱未开启“头像浮动”功能的前提下开启MSpring的“连续消息合并”功能时，消息合并功能无法生效。
![只开启mspring](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/20354136/f2c028f5-9fce-4cf6-88bc-7aeecb4648c2)只开启mspring的效果
![两者同时开启](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/20354136/d06a9460-50b4-4f5d-8ca0-7c0feb7c4e7c)两者同时开启的效果

如果能告知我需要提供什么日志文件的话，很乐意提供。此issue在两个插件都发了

**Comment by MUKAPP** [comment]
建议弃用MSpring的消息合并功能，使用轻量工具箱的

**Comment by MUKAPP** [comment]
> 建议弃用MSpring的消息合并功能，使用轻量工具箱的 Message ID: ***@***.***&gt;

另外MSpring的消息合并功能之前就打算删掉了，bug太多，而且轻量工具箱的那个明显更好用（）
