### ISSUE TITLE
链接重复显示

### ISSUE THREAD

**Issue by LINKlang** [MUKAPP/BetterQQNT-MSpring-Theme#49]
当文字中有链接时，会从链接开始，把后面的重复显示一遍，只开主题也会这样，关了就没事
版本：9.9.0.14619
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/116951234/8f3197ac-997d-49b2-bf3c-e7bf3a3edb07)

**Comment by MUKAPP** [comment]
15717&16183无法复现

**Comment by LINKlang** [comment]
> 15717&16183无法复现

QQ9.9.0.14619链接：https://1drv.ms/u/s!AnnH5DL_ZfpzhTC7CtSxbcb8hhEr?e=GaZ9jP
可以试试用这个版本
设置：
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/116951234/3c4e1bf8-f756-493e-919b-3268ef41eba3)

**Comment by LINKlang** [comment]
更新到9.9.2.16183后解决了
