### ISSUE TITLE
配置界面不显示

### ISSUE THREAD

**Issue by S-t-e-v-e-e** [MUKAPP/BetterQQNT-MSpring-Theme#50]
最新版
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/117198625/874edcbc-e2fd-4d3c-848f-860606fa67b4)

**Comment by MUKAPP** [comment]
之前版本有出现过吗

**Comment by MUKAPP** [comment]
已修复，请重新下载最新版本
