### ISSUE TITLE
希望适配QQ频道背景模糊

### ISSUE THREAD

**Issue by S-t-e-v-e-e** [MUKAPP/BetterQQNT-MSpring-Theme#51]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/117198625/9eb99090-f67f-4ac6-b4a0-5b0cf2173bfd)

**Comment by MUKAPP** [comment]
频道窗口背景tx本来就没写模糊w，暂时做不了

**Comment by MUKAPP** [comment]
见最新版
