### ISSUE TITLE
升级插件版本报错,清除数据目录\LiteLoaderQQNT\plugins_data\mspring_theme

### ISSUE THREAD

**Issue by Piracola** [MUKAPP/BetterQQNT-MSpring-Theme#53]
<img width="270" alt="Snipaste_2023-12-25_10-21-27" src="https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/116626041/fdee20f9-0452-4d8b-be1d-b79dc5d19a87">

1.0.5升级1.0.6之后要清除插件缓存,不然会报错x
昨天打开qq就弹窗报错,找了俩小时才发现是有插件不兼容,稀里糊涂的找了好久发现是这个插件有问题,经过半个小时的摸索后发现,删除\LiteLoaderQQNT\plugins_data\mspring_theme后重启qq就好了
我好傻
~~希望不会有人和我一样傻吧~~

**Comment by MUKAPP** [comment]
？![Image_1703473566822.gif](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/7d1f253c-b514-4808-a162-22e2d88c0c1b)
