### ISSUE TITLE
1.1.9 无法通过LL应用商店安装

### ISSUE THREAD

**Issue by Simplxss** [MUKAPP/BetterQQNT-MSpring-Theme#55]
Release 1.1.9 中没有包含 [LiteLoaderQQNT-MSpring-Theme.zip](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/releases/download/v1.1.9/LiteLoaderQQNT-MSpring-Theme.zip) 导致应用商店无法下载插件

**Comment by MUKAPP** [comment]
加上了
我大抵是傻了（）
