### ISSUE TITLE
背景顏色透明度無法影響輕量工具箱配置頁面

### ISSUE THREAD

**Issue by shi-an** [MUKAPP/BetterQQNT-MSpring-Theme#56]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/79352488/0e8087d4-764b-4721-af6b-58720d943bce)

**Comment by MUKAPP** [comment]
这是因为轻量工具箱还没有使用最新的由liteloader提供的组件，我是按那个统一适配的

**Comment by MUKAPP** [comment]
轻量工具箱新版已适配
