### ISSUE TITLE
[Bug] 深色模式(夜间模式)下 自己发出的消息里面 @/链接 因为跟随主题颜色导致难以看清

### ISSUE THREAD

**Issue by RF-Tar-Railt** [MUKAPP/BetterQQNT-MSpring-Theme#58]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/42648639/59406dfe-45fb-4fea-8f85-e49ed1cabb8d)
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/42648639/213471ba-80e5-4ba3-b036-f5e97e129170)
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/42648639/53eb8c63-8897-4833-b70d-120e22fc920a)

或许可以考虑配置一下at / 链接的颜色？

**Comment by zhulinyv** [comment]
我额外设置了艾特的颜色

![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/66541860/6d4f0be6-30e5-46e0-ad47-0a48d5d2939a)
