### ISSUE TITLE
代码里多处死循环，奇葩的是居然能跑

### ISSUE THREAD

**Issue by adoin** [MUKAPP/BetterQQNT-MSpring-Theme#62]
比如
updateStyle
底下有webContents.send
发送事件
又会执行updateStyle

。。。

**Comment by MUKAPP** [comment]
你说的对，上去丢人

**Comment by hacker-frok** [comment]
> 比如 updateStyle 底下有webContents.send 发送事件 又会执行updateStyle
> 
> 。。。

哥们，多看看Electron 再发话..

**Comment by adoin** [comment]
> > 比如 updateStyle 底下有webContents.send 发送事件 又会执行updateStyle
> > 。。。
> 
> 哥们，多看看Electron 再发话..

emmm 我做了个插件拿这个改的，启动不了，去掉这些就启动了啊。
Electron是不太熟，不过你们都说对，那肯定是对的，我听劝
