### ISSUE TITLE
【适配】主题的小适配问题

### ISSUE THREAD

**Issue by RingingVolcano** [MUKAPP/BetterQQNT-MSpring-Theme#64]
分享窗口的列表与顶部的“最近聊天”有重叠
![b50975c6255c5683714c607e48ae06c5](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/72140353/b87ff51d-dc9c-4a8f-89d6-62c9f22853a6)

**Comment by MUKAPP** [comment]
mac吗？

**Comment by MUKAPP** [comment]
已修复
