### ISSUE TITLE
自身消息颜色渲染

### ISSUE THREAD

**Issue by misaka10384** [MUKAPP/BetterQQNT-MSpring-Theme#67]
如果可以  能否给这个自身消息的渲染加个开关   
我只想用这个插件修改主题色 
但不想渲染自身的消息的颜色  
但肯定有人用得上 
比如那些开了头像浮动 消息合并 头像置底的同时开了消息靠左的人  
所以 能不能加个开关.jpg
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/61707010/6b5e8e1f-889a-4570-9b6f-63d19985129c)

**Comment by MUKAPP** [comment]
如果消息靠左但是又不区分气泡颜色的话，那岂不是很容易混吗

**Comment by misaka10384** [comment]
> 如果消息靠左但是又不区分气泡颜色的话，那岂不是很容易混吗

对  开启消息靠左的人就需要用到自身消息颜色渲染  所以我希望你能怼个开关进去   因为这个消息颜色渲染看的我眼睛疼  或者把消息颜色渲染跟主题分离出来单独设置

**Comment by MUKAPP** [comment]
虽然还没做这个功能，但是现在在开启修改背景的插件的时候它们会把主题的覆盖掉，算是暂时变相解决了你的问题（）
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/0f244c05-b9c8-4ca1-b081-f20245479429) 轻量工具箱
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/72ef7490-c20d-430a-b2e5-d59855f28606) 背景插件

**Comment by yhzcake** [comment]
> 虽然还没做这个功能，但是现在在开启修改背景的插件的时候它们会把主题的覆盖掉，算是暂时变相解决了你的问题（） ![image](https://private-user-images.githubusercontent.com/41848070/311444987-0f244c05-b9c8-4ca1-b081-f20245479429.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzQ1MzgsIm5iZiI6MTcxMDY3NDIzOCwicGF0aCI6Ii80MTg0ODA3MC8zMTE0NDQ5ODctMGYyNDRjMDUtYjljOC00Y2ExLWIwODEtZjIwMjQ1NDc5NDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDExMTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNjVjY2NiOWI3ZGNjZTM4NWQ4ZmNiZGQ3ZjBiOTk5ZWY3ODM5NmQyZTI1YjhjZTQ3OWViZDRmMTQyNjdhMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D31qL1Qsdaka_wxEBcb0ya8CRJcvThYWhusPE5U9ktc) 轻量工具箱 ![image](https://private-user-images.githubusercontent.com/41848070/311445201-72ef7490-c20d-430a-b2e5-d59855f28606.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzQ1MzgsIm5iZiI6MTcxMDY3NDIzOCwicGF0aCI6Ii80MTg0ODA3MC8zMTE0NDUyMDEtNzJlZjc0OTAtYzIwZC00MzBhLWIyZTUtZDU5ODU1ZjI4NjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDExMTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NGU1MGEyY2VmNGZmYWY3YmUxYjc1ZTI0Mjc0ZDE1OGQxNmJjMDM2ZDk1MjZjZTMwMTdlMzdiYzkxNzk2MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eGfIB5vpoXP8v7p5FFa2wCoxYZMnqfFEBKyFGxkvgmA) 背景插件

你说的对,但是我需要渲染主题色...
所以怎么样能让自己的主题色重新渲染回来啊.急

**Comment by MUKAPP** [comment]
> 你说的对,但是我需要渲染主题色... 所以怎么样能让自己的主题色重新渲染回来啊.急

现在是别人的插件覆盖了我的样式，如果我再去强行覆盖可能会出现兼容问题

**Comment by MUKAPP** [comment]
> 你说的对,但是我需要渲染主题色... 所以怎么样能让自己的主题色重新渲染回来啊.急

我之后可能会写相关的功能，你要实在急的话要么你就先只用提供背景功能的插件，关掉主题，要么你就先只用主题，关掉提供背景功能的插件。你要是非要两个一起用还急着要我改的话那你先别急

**Comment by yhzcake** [comment]
> > 你说的对,但是我需要渲染主题色... 所以怎么样能让自己的主题色重新渲染回来啊.急
> 
> 现在是别人的插件覆盖了我的样式，如果我再去强行覆盖可能会出现兼容问题


但是v1.2.3是正常可以渲染主题色的,而且后面版本在打开qq的登录界面貌似是透明的能看到原本qq那个动效的蓝色,很丑

所以如果这两个地方没有办法修改的话我大概率会选择不再进行版本更新了...

另外邮箱通知有办法也设置成透明并且尽量横向占据界面吗?

**Comment by MUKAPP** [comment]
> 但是v1.2.3是正常可以渲染主题色的,而且后面版本在打开qq的登录界面貌似是透明的能看到原本qq那个动效的蓝色,很丑
> 
> 所以如果这两个地方没有办法修改的话我大概率会选择不再进行版本更新了...
> 
> 另外邮箱通知有办法也设置成透明并且尽量横向占据界面吗?

邮箱通知、卡片通知那些改不了
登录页面现在背景跟主页一样，都是模糊的窗口后面的内容，QQ的动效我之前删掉了的
代码之前整个优化了，很多东西不是直接修改元素，而是修改元素使用的颜色，所以会被其他插件覆盖
你要是能暂时接受那你就别急，你要是接受不了那你就回退版本

**Comment by yhzcake** [comment]
> > 但是v1.2.3是正常可以渲染主题色的,而且后面版本在打开qq的登录界面貌似是透明的能看到原本qq那个动效的蓝色,很丑
> > 所以如果这两个地方没有办法修改的话我大概率会选择不再进行版本更新了...
> > 另外邮箱通知有办法也设置成透明并且尽量横向占据界面吗?
> 
> 邮箱通知、卡片通知那些改不了 登录页面现在背景跟主页一样，都是模糊的窗口后面的内容，QQ的动效我之前删掉了的 代码之前整个优化了，很多东西不是直接修改元素，而是修改元素使用的颜色，所以会被其他插件覆盖 你要是能暂时接受那你就别急，你要是接受不了那你就回退版本

哦,是代码大改的结果
那我就在1.2.3吧,挺好的

**Comment by yhzcake** [comment]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/80627671/792640c9-1c33-41c2-a8ed-a0190b463d59)
这个暗黑模式自己的消息也是这么控制的吗,我更新了之后是这个颜色,看不清字

**Comment by MUKAPP** [comment]
> ![image](https://private-user-images.githubusercontent.com/80627671/316318438-792640c9-1c33-41c2-a8ed-a0190b463d59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyOTM0MTksIm5iZiI6MTcxMTI5MzExOSwicGF0aCI6Ii84MDYyNzY3MS8zMTYzMTg0MzgtNzkyNjQwYzktMWMzMy00MWMyLWE4ZWQtYTAxOTBiNDYzZDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE1MTE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0OGQzN2U1ODc1ZjkyNTI2ODIyZGNhNDI0NGJkOGQxMzEyZDIyMDZlMmFkMmY3M2FkMjFmYzIxY2UzOGI5MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V4V1kBVV3DX2Mqa6AfxgTwymXE48HbOsBmaUgK3PqBo) 这个暗黑模式自己的消息也是这么控制的吗,我更新了之后是这个颜色,看不清字

这个是样式冲突了，我下个版本修一下

**Comment by yhzcake** [comment]
> > ![image](https://private-user-images.githubusercontent.com/80627671/316318438-792640c9-1c33-41c2-a8ed-a0190b463d59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyOTM0MTksIm5iZiI6MTcxMTI5MzExOSwicGF0aCI6Ii84MDYyNzY3MS8zMTYzMTg0MzgtNzkyNjQwYzktMWMzMy00MWMyLWE4ZWQtYTAxOTBiNDYzZDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE1MTE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0OGQzN2U1ODc1ZjkyNTI2ODIyZGNhNDI0NGJkOGQxMzEyZDIyMDZlMmFkMmY3M2FkMjFmYzIxY2UzOGI5MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V4V1kBVV3DX2Mqa6AfxgTwymXE48HbOsBmaUgK3PqBo) 这个暗黑模式自己的消息也是这么控制的吗,我更新了之后是这个颜色,看不清字
> 
> 这个是样式冲突了，我下个版本修一下

好

**Comment by MUKAPP** [comment]
> ![image](https://private-user-images.githubusercontent.com/80627671/316318438-792640c9-1c33-41c2-a8ed-a0190b463d59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDAwMjUsIm5iZiI6MTcxMjE5OTcyNSwicGF0aCI6Ii84MDYyNzY3MS8zMTYzMTg0MzgtNzkyNjQwYzktMWMzMy00MWMyLWE4ZWQtYTAxOTBiNDYzZDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDAzMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNzQxYTQyMzkxYWI5N2Q3NWZlMzcwNDcxYmY0MGUyZTg1Njg1OWIzMDYyMTY3YmE1MmMzOGZmNGVkOTExYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KuF9B5EAhLQtfSVTyspTEh1-TMrTESsB9rQRDRkxIJ0) 这个暗黑模式自己的消息也是这么控制的吗,我更新了之后是这个颜色,看不清字

你这个是如何触发的，我这里无法触发

**Comment by MUKAPP** [comment]
> 你这个是如何触发的，我这里无法触发

知道了，是背景插件

**Comment by yhzcake** [comment]
> 知道了，是背景插件

原来是这样,那这个能修吗,我看背景插件的作者貌似不更新了

**Comment by MUKAPP** [comment]
> 原来是这样,那这个能修吗,我看背景插件的作者貌似不更新了

在修

**Comment by misaka10384** [comment]
加油啊  写代码的大哥哥

**Comment by MUKAPP** [comment]
现在应该可以了

**Comment by yhzcake** [comment]
> ...在打开qq的登录界面貌似是透明的能看到原本qq那个动效的蓝色,很丑

更新了新版本的liteloader之后貌似又出现了这个bug...

**Comment by MUKAPP** [comment]
> 更新了新版本的liteloader之后貌似又出现了这个bug...

¿

**Comment by yhzcake** [comment]
> ¿

![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/80627671/3ca410c1-6773-4b1d-b310-8f086c7547e8)
大概就是这样,liteloader更新到1.1.0了,基本所有插件都或多或少有点bug,乐
应该是MoreMaterials的问题...
我把MoreMaterials关了没事了

**Comment by MUKAPP** [comment]
> 应该是MoreMaterials的问题...
> 我把MoreMaterials关了没事了

xing
