### ISSUE TITLE
群成员间距是否过大

### ISSUE THREAD

**Issue by huoyan1231** [MUKAPP/BetterQQNT-MSpring-Theme#68]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/53113734/ebfa9265-1572-4b00-ab45-7a0fee854961)

**Comment by MUKAPP** [comment]
可能之前改什么误伤到群成员列表了，一直没发现

**Comment by huoyan1231** [comment]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/53113734/1ac7fc37-2e5a-4883-9506-95e87bcd482f)
补充一张没有主题的

**Comment by MUKAPP** [comment]
已修复
