### ISSUE TITLE
收藏夹内全白

### ISSUE THREAD

**Issue by suiniara** [MUKAPP/BetterQQNT-MSpring-Theme#69]
![3dc110df888e2928c67b30385bff2a71](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/33367461/c3ca48d6-880e-41c2-aa47-f8ab4a9cda78)
收藏夹内全白

**Comment by MUKAPP** [comment]
说一下你的系统版本、日间模式还是夜间模式，截图一下主题设置

**Comment by suiniara** [comment]
![c8e4597226b4ac2a15262985e23abd36](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/33367461/d96ab146-4608-43a0-b361-75a016b1fbeb)
![fcf842968c86f19a0d6a69767e525d05](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/33367461/e4b9cbbe-77c4-4716-bc31-0ff1a1f9a674)

![9e6d660a9ec088cbd1f5a96645620eda](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/33367461/05624215-2d3d-4e50-b4e5-294b3e0dfc71)
另外不关闭主题的话 `关于` 也是纯白的
我是的系统是深色模式

**Comment by MUKAPP** [comment]
无法复现呢。。
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/2bdce864-4866-494d-b7b2-8272abd5a8d3)

**Comment by xiyuesaves** [comment]
我找到这个问题且复现了，和这个问题是一样的 [[Bug]: 背景在深色模式下无法覆盖侧边栏的问题](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools/issues/141) 产生原因是如果 QQ 没有开启透明效果或者操作系统不兼容的话，窗口的背景色会固定为 白色/黑色(取决于关闭透明效果时选择的主题) 此时由于我们都删除了 QQ 自带背景色，就会导致在暗色模式下窗口是白色且窗口内图标也是白色的问题

**Comment by MUKAPP** [comment]
> 我找到这个问题且复现了，和这个问题是一样的 [[Bug]: 背景在深色模式下无法覆盖侧边栏的问题](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools/issues/141) 产生原因是如果 QQ 没有开启透明效果或者操作系统不兼容的话，窗口的背景色会固定为 白色/黑色(取决于关闭透明效果时选择的主题) 此时由于我们都删除了 QQ 自带背景色，就会导致在暗色模式下窗口是白色且窗口内图标也是白色的问题

okk，谢谢小曦月
![0f8a2091a08daa173ecee87ec5812e97](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/a05f9cc0-9c36-4e4b-b289-7484fea0999c)

**Comment by MUKAPP** [comment]
已修复
