### ISSUE TITLE
链接文字颜色与消息气泡颜色重合

### ISSUE THREAD

**Issue by jackwd387** [MUKAPP/BetterQQNT-MSpring-Theme#7]
链接文字颜色与消息气泡颜色重合
![279f9a4bd6bb64f5355570c4a2d48f72](https://github.com/MUKAPP/BetterQQNT-MSpring-Theme/assets/105554762/561c2f10-14b3-4279-8872-a1d6e0e7b27a)

**Comment by MUKAPP** [comment]
之前修了，但是没发release，刚刚发了0.1.5
