### ISSUE TITLE
优化消息排版功能在特定场合的显示效果不佳

### ISSUE THREAD

**Issue by InfSein** [MUKAPP/BetterQQNT-MSpring-Theme#70]
例如

> [QQ红包]拿去买肯德基，我不像别人只会嘴上说说，我还会复制

在这个示例中，`Q`为英文，因此与`[`合并；`包`与`拿`为中文，因此`]`与它们有间隔

于是最后显示的效果就有点不协调
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/54071139/0753f89d-b52f-4623-8db1-cd0b52432845)

**Comment by MUKAPP** [comment]
优化消息排版功能使用 [赫蹏](https://github.com/sivan/heti) 实现
