### ISSUE TITLE
加群窗口回答问题区域完全看不见

### ISSUE THREAD

**Issue by bd-dxg** [MUKAPP/BetterQQNT-MSpring-Theme#72]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/34816426/d39d867d-b88e-4634-9287-bae1ed469f5d)

这里应该有个框输入答案的 但是完全看不见了 希望能优化一下

**Comment by MUKAPP** [comment]
已修复
