### ISSUE TITLE
qq群和频道中使用/机器人指令也会变得透明

### ISSUE THREAD

**Issue by viodnomad** [MUKAPP/BetterQQNT-MSpring-Theme#73]
![5ec6890619f2f1ec27f8b427bd89a56d](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/111840192/c7c5d919-15c6-42af-88a6-885e28995914)
![03c767a5f3e59eb7fcd118961ec87364](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/111840192/2862cc87-9b34-4dfc-a5e5-8277fc46020a)

**Comment by viodnomad** [comment]
![258d3480d00da784feac23c1135342f0](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/111840192/7bff3b0b-670b-4036-a1d8-4a76f0929bd7)
![95be7693a810c7347fb3a48fa0cdfe62](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/111840192/df5ad56d-78ab-4a59-b893-49d31b36825f)
取消使用后变为正常

**Comment by yhzcake** [comment]
对的,希望尽快修复,很难看清

**Comment by SoudayoWwww** [comment]
![1](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/52328223/af11f791-37be-4145-8f3d-f1b50e71345d)
![3](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/52328223/2173ed10-1cb5-4b5d-804c-00ea1c3b7e1d)

@指令也会触发该bug

**Comment by MUKAPP** [comment]
已修复
