### ISSUE TITLE
1.2.8版本登陆页面背景颜色与之前版本不同

### ISSUE THREAD

**Issue by LINKlang** [MUKAPP/BetterQQNT-MSpring-Theme#74]
以前版本的背景都是黑灰色的，但是在更新1.2.8后，背景颜色被修改成了HEX：#171726
若是bug希望修复，如果是特地的，希望加入修改选项
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/116951234/7d29535e-8ffb-4964-9d5d-383eef2b8bd5)

**Comment by MUKAPP** [comment]
登录页面现在跟主页一样删掉了背景，会直接模糊窗口后面的内容

**Comment by LINKlang** [comment]
> 登录页面现在跟主页一样删掉了背景，会直接模糊窗口后面的内容

是否可以添加登陆页面背景的是否删除的选项

**Comment by MUKAPP** [comment]
已修复
