### ISSUE TITLE
文件管理器界面优化

### ISSUE THREAD

**Issue by nogodnodevil** [MUKAPP/BetterQQNT-MSpring-Theme#79]
1.文件管理器最上边的时间栏是透明的（如图），不太协调，能不能增加背景色
![PixPin_2024-04-11_16-30-39](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/151034627/bd7f93cc-d114-473c-b1bb-5c1c700a1dd4)
2.文件管理器往下拉到底，会出现白色条框（如图），能不能修复
![PixPin_2024-04-11_16-31-12](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/151034627/8b4ad8dd-15a9-4920-9f3e-2031982a4c9f)

**Comment by nogodnodevil** [comment]
3.联系人页面的好友/群聊背景为白色，有点突兀，能不能调整
![PixPin_2024-04-11_16-35-05](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/151034627/04ccf397-7048-4d73-80db-946f12a27c2c)

**Comment by xinyihl** [comment]
> 2.文件管理器往下拉到底，会出现白色条框（如图），能不能修复

![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/75861358/ab7522fb-2bbe-4baf-989f-ddbb9190c7b2)
逆天腾讯通过判断他是否出现在屏幕里来继续加载文件列表
设置成 none 就不加载列表了可还行

**Comment by nogodnodevil** [comment]
> > 2.文件管理器往下拉到底，会出现白色条框（如图），能不能修复
> 
> ![image](https://private-user-images.githubusercontent.com/75861358/322205155-ab7522fb-2bbe-4baf-989f-ddbb9190c7b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNjU0MjcsIm5iZiI6MTcxMzA2NTEyNywicGF0aCI6Ii83NTg2MTM1OC8zMjIyMDUxNTUtYWI3NTIyZmItMmJiZS00YmFmLTk4OWYtZGRiYjkxOTBjN2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDAzMjUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MmZkYzAyMWIxNjU1MjE4MzU2MDA1OTNkMTdkNWMwOTNmNjVmMGE4MTQ5OWJlOTJjNmI1ZTc1Yjc0OWQwYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uGdGVpZs9o4i4GAAmYZ4PKH-GQ-tQsBrrM2pnMXUNqQ) 逆天腾讯通过判断他是否出现在屏幕里来继续加载文件列表 设置成 none 就不加载列表了可还行

我暂时把它的宽度设置为0，既不显示，也会加载，完美！
.loadmore-placeholder{
    width:0% !important;
}
