### ISSUE TITLE
白天模式下加载出错

### ISSUE THREAD

**Issue by jackwd387** [MUKAPP/BetterQQNT-MSpring-Theme#8]
不知是不是没有用betterqqnt（js）插件的问题
![356c3ce26a09b5d07f5453f4420e2b87](https://github.com/MUKAPP/BetterQQNT-MSpring-Theme/assets/105554762/0124e46b-bf7e-4f76-b83e-816942d77b16)

**Comment by MUKAPP** [comment]
该主题为 [mo-jinran/BetterQQNT](https://github.com/mo-jinran/BetterQQNT) 的插件，未在其他地方测试过，你可以在安装 [mo-jinran/BetterQQNT](https://github.com/mo-jinran/BetterQQNT) 之后再试
