### ISSUE TITLE
使用本插件并配合使用 More Materials 插件后渲染异常

### ISSUE THREAD

**Issue by Reversedeer** [MUKAPP/BetterQQNT-MSpring-Theme#81]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/87823528/c718d566-523f-4145-9cf1-aec46c81b80e)
单独使用本插件没有问题,初步认为是与More-Materials不适配的问题？

系统: windows 10 22H2

QQNT：9.9.9-22961

LiteLoaderQQNT-MSpring-Theme: 1.3.1

More-Materials: 1.0.0

**Comment by MUKAPP** [comment]
win10为什么要用more material？

**Comment by MUKAPP** [comment]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/d71e1bf1-adae-4cfb-9246-7e813a9e25c6)

**Comment by Reversedeer** [comment]
忽略了虚拟机里是win10，其实自己在用win11，抱歉哈
