### ISSUE TITLE
搜索框异常！！！

### ISSUE THREAD

**Issue by GWNLP** [MUKAPP/BetterQQNT-MSpring-Theme#82]
重影（只开了这个主题，没有开其他插件）
<img width="189" alt="20240517_202550" src="https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/118590347/aad1c75c-c014-4381-a8c8-806124d25a72">

**Comment by GWNLP** [comment]
<img width="189" alt="20240517_202550" src="https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/118590347/f36cc54b-5e72-4044-af62-370bf095879c">

**Comment by MUKAPP** [comment]
无法复现
请提供你的QQ版本、LiteLoaderQQNT版本、系统版本

**Comment by MUKAPP** [comment]
太长时间没回复，先关掉了
