### ISSUE TITLE
渲染异常

### ISSUE THREAD

**Issue by KelseySking** [MUKAPP/BetterQQNT-MSpring-Theme#83]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/62224263/8378bc52-ee10-4f9e-a55b-c8db04ee84b9)
有的标题那一行颜色不一致

**Comment by MUKAPP** [comment]
无法复现，有更多信息吗

**Comment by forgetmelodyXL** [comment]
我也出现了这种情况，但并不是刚安装就出现这个问题的，关闭MSpring-Theme插件则恢复正常
重新安装liteloaderQQNT和MSpring-Theme不能解决问题

**Comment by KelseySking** [comment]
> 无法复现，有更多信息吗

llqt版本
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/62224263/3c017580-fe3c-4e88-961c-72f45a476019)

我这是win10系统
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/62224263/8badfcca-f874-408a-b0f6-abfddb689f52)
并且我的两台电脑都有这种渲染问题
这是另一台电脑
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/62224263/b58550b0-3283-4335-b63d-97d9925729d4)

**Comment by MUKAPP** [comment]
我也是win10
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/1db67628-b197-418c-874f-d517720f6031)
怪了

**Comment by MUKAPP** [comment]
经排查，是在 LiteLoaderQQNT/LiteLoaderQQNT@3d434c61ff197284327327508c09065c38c88d21 更改之后出现问题，建议先使用 LiteLoaderQQNT release 的最新版本 1.1.1，而不是直接 clone 仓库
@KelseySking @asd13852710118

**Comment by KelseySking** [comment]
> 经排查，是在 [LiteLoaderQQNT/LiteLoaderQQNT@3d434c6](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/commit/3d434c61ff197284327327508c09065c38c88d21) 更改之后出现问题，建议先使用 LiteLoaderQQNT release 的最新版本 1.1.1，而不是直接 clone 仓库 @KelseySking @asd13852710118

ok，感谢
