### ISSUE TITLE
[bug]  打开的独立窗口不支持聊天框透明

### ISSUE THREAD

**Issue by sakura-ender** [MUKAPP/BetterQQNT-MSpring-Theme#85]
右键--打开独立聊天窗口，打开的聊天窗口不支持透明
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/117716855/60ac5ff7-3bf2-4ded-b435-95cbbb052e47)

**Comment by MUKAPP** [comment]
搭配 [More Materials](https://github.com/mo-jinran/More-Materials) 插件使用
