### ISSUE TITLE
[Bug] 设置页Switch渲染异常

### ISSUE THREAD

**Issue by adproqwq** [MUKAPP/BetterQQNT-MSpring-Theme#86]
rt
![01b3e0679d38d1ba324f34c6cab32399](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/101449500/78929983-be84-4507-bf58-7a932b653b9a)

强行覆盖自己发送的气泡颜色 选项，Switch的渲染似乎有些问题

**Comment by MUKAPP** [comment]
已修复
