### ISSUE TITLE
覆盖自己气泡颜色失效

### ISSUE THREAD

**Issue by shibuyameltdown** [MUKAPP/BetterQQNT-MSpring-Theme#87]
qqnt版本9.9.11-24616 (64位)
liteloader版本1.1.1
mspring版本1.3.3
且侧边栏颜色变成qq自带夜间模式的黑色
![b5d17ef9-59fd-4b70-86d0-a0d66ec48e96](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/78797438/b67ec0a9-e943-451b-aa0c-f640a0707c0e)

**Comment by MUKAPP** [comment]
经测试，24815 正常
![956e44309b3f5179e95b3bd6460ac49f_720](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/66ebcaa7-949b-47ed-a8e2-4160efee95f7)

**Comment by shibuyameltdown** [comment]
有更新吗？我检查更新提示24616是最新

**Comment by MUKAPP** [comment]
> 有更新吗？我检查更新提示24616是最新

- Windows: 
X86 (https://dldir1.qq.com/qqfile/qq/QQNT/55e6c448/QQ9.9.11.24815_x86.exe) | X64 (https://dldir1.qq.com/qqfile/qq/QQNT/c3b55e07/QQ9.9.11.24815_x64.exe) | Arm (https://dldir1.qq.com/qqfile/qq/QQNT/49bdc590/QQ9.9.11.24815_arm64.exe)

**Comment by shibuyameltdown** [comment]
> > 有更新吗？我检查更新提示24616是最新
> 
> * Windows:
>   X86 (https://dldir1.qq.com/qqfile/qq/QQNT/55e6c448/QQ9.9.11.24815_x86.exe) | X64 (https://dldir1.qq.com/qqfile/qq/QQNT/c3b55e07/QQ9.9.11.24815_x64.exe) | Arm (https://dldir1.qq.com/qqfile/qq/QQNT/49bdc590/QQ9.9.11.24815_arm64.exe)

已解决
