### ISSUE TITLE
[Bug] 设置界面渲染异常

### ISSUE THREAD

**Issue by Cranyozen** [MUKAPP/BetterQQNT-MSpring-Theme#88]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/61766249/2422a6bc-8628-4f8e-b46f-6979ce2438ae)
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/61766249/457a2e14-dc62-4717-bcdc-af58f2c168b4)
如图

另外，改变主题色后仍然会出现 #80 的问题

**Comment by MUKAPP** [comment]
渲染异常见 #83，在 llqt 新的正式版发布之前不打算修复，另外推荐你用 release 的正式版
#80 无法修复，连 llqt 开发者都不知道是什么原因

**Comment by MUKAPP** [comment]
更新至 LiteLoaderQQNT 1.1.2 即可解决
