### ISSUE TITLE
插件bug

### ISSUE THREAD

**Issue by Starrain08** [MUKAPP/BetterQQNT-MSpring-Theme#89]
主题颜色设置失效
![QQ_1720946313091](https://github.com/user-attachments/assets/e03927e9-0c3f-4c4f-b868-eafaca6838c1)

**Comment by Starrain08** [comment]
![QQ_1720946375856](https://github.com/user-attachments/assets/eaf42b01-7cf3-4acb-a679-315f74f9d406)

**Comment by MUKAPP** [comment]
更新到最新版看看
