### ISSUE TITLE
聊天输入框拉伸后遮挡消息、没有呈现出圆角

### ISSUE THREAD

**Issue by FinaFina233** [MUKAPP/BetterQQNT-MSpring-Theme#9]
![image](https://github.com/MUKAPP/BetterQQNT-MSpring-Theme/assets/52440333/f778efa0-9900-4906-a108-29f8c8634338)

**Comment by Simple-Young** [comment]
hhhhm, 严重bug
![image](https://github.com/MUKAPP/BetterQQNT-MSpring-Theme/assets/54128779/d34bc7e8-c153-4e09-947b-ecab4118f8d9)

**Comment by MUKAPP** [comment]
新版已修复（）
