### ISSUE TITLE
过去是正常的，但不知道为什么突然炸了

### ISSUE THREAD

**Issue by Dreamtell** [MUKAPP/BetterQQNT-MSpring-Theme#90]
_错误信息：_
[Main] Unexpected token '�', "����������"... is not valid JSON
SyntaxError: Unexpected token '�', "����������"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\Users\28278\Documents\LiteloaderQQNT\plugins\LiteLoaderQQNT-MSpring-Theme\main.js:197:25)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at f._load (node:electron/js2c/node_init:2:18640)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.init (C:\Program Files\Tencent\QQNT\resources\app\LiteLoaderQQNT-main\src\main.js:18:43)
_插件信息：_
{"manifest":{"manifest_version":4,"type":"theme","name":"MSpring Theme","slug":"mspring_theme","description":"LiteLoaderQQNT 主题，优雅 · 粉粉 · 细致","version":"1.3.3","icon":"./res/icon.png","thumb":"./res/brush_FILL0_wght300_GRAD0_opsz24.svg","authors":[{"name":"MUKAPP","link":"https://github.com/MUKAPP"}],"platform":["win32","linux","darwin"],"injects":{"renderer":"./renderer.js","main":"./main.js","preload":"./preload.js"},"repository":{"repo":"MUKAPP/LiteLoaderQQNT-MSpring-Theme","branch":"v4","release":{"tag":"latest","file":"LiteLoaderQQNT-MSpring-Theme.zip"}}},"incompatible":false,"disabled":false,"path":{"plugin":"C:\\Users\\28278\\Documents\\LiteloaderQQNT\\plugins\\LiteLoaderQQNT-MSpring-Theme","data":"C:\\Users\\28278\\Documents\\LiteloaderQQNT\\data\\mspring_theme","injects":{"main":"C:\\Users\\28278\\Documents\\LiteloaderQQNT\\plugins\\LiteLoaderQQNT-MSpring-Theme\\main.js","preload":"C:\\Users\\28278\\Documents\\LiteloaderQQNT\\plugins\\LiteLoaderQQNT-MSpring-Theme\\preload.js","renderer":"C:\\Users\\28278\\Documents\\LiteloaderQQNT\\plugins\\LiteLoaderQQNT-MSpring-Theme\\renderer.js"}},"error":{"message":"[Main] Unexpected token '\u0000', \"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\"... is not valid JSON","stack":"SyntaxError: Unexpected token '\u0000', \"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\"... is not valid JSON\n    at JSON.parse (<anonymous>)\n    at Object.<anonymous> (C:\\Users\\28278\\Documents\\LiteloaderQQNT\\plugins\\LiteLoaderQQNT-MSpring-Theme\\main.js:197:25)\n    at Module._compile (node:internal/modules/cjs/loader:1373:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)\n    at Module.load (node:internal/modules/cjs/loader:1215:32)\n    at Module._load (node:internal/modules/cjs/loader:1031:12)\n    at f._load (node:electron/js2c/node_init:2:18640)\n    at Module.require (node:internal/modules/cjs/loader:1240:19)\n    at require (node:internal/modules/helpers:179:18)\n    at Object.init (C:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\src\\main.js:18:43)"}}

["background_plugin","deepl_plugin","directly_jump","justf5","link_preview","list-viewer","mspring_theme","qr_code","LiteLoaderQQNT_CheckUpdateModule","lite_tools","media_local_view","plugininstaller","purlfy","anti_recall","QuickReply"]
_环境信息：_
{"qqnt":"9.9.12-25493","liteloader":"1.1.2","node":"20.14.0","chrome":"126.0.6478.36","electron":"31.0.1","platform":"win32"}

**Comment by MUKAPP** [comment]
重装插件试试
