### ISSUE TITLE
windowsQQ移除了透明效果

### ISSUE THREAD

**Issue by CNReporter** [MUKAPP/BetterQQNT-MSpring-Theme#91]
QQ在9.9.12-25765版本的热补丁更新移除了透明效果，导致插件的透明基本不生效了，是否可以修复这个问题？

**Comment by DoneBootbloader** [comment]
一样

**Comment by xiyuesaves** [comment]
安装 [More-Materials](https://github.com/mo-jinran/More-Materials)

**Comment by CNReporter** [comment]
> 安装 [More-Materials](https://github.com/mo-jinran/More-Materials)

我装了没什么效果啊 怎么设置的

**Comment by MUKAPP** [comment]
> 我装了没什么效果啊 怎么设置的

昨天修了，等主题新版本发布吧

**Comment by CNReporter** [comment]
> > 我装了没什么效果啊 怎么设置的
> 
> 昨天修了，等主题新版本发布吧

关闭窗体再通过任务栏重新打开或者登录完切换会话透明效果有概率消失，版本号是2.31.0

**Comment by MUKAPP** [comment]
更新到最新版看看

**Comment by CNReporter** [comment]
> 更新到最新版看看

没有生效
![QQ_1721120927267](https://github.com/user-attachments/assets/51c87d56-24bc-4c25-a339-a44f0808f868)

**Comment by MUKAPP** [comment]
> 没有生效

需要搭配 More Materials 插件

**Comment by CNReporter** [comment]
> 关闭窗体再通过任务栏重新打开或者登录完切换会话透明效果有概率消失

出现了跟上面的工具箱一样的问题，关闭窗体再通过任务栏重新打开或者登录完切换会话透明效果有概率消失

出现这个情况之后需要去Material插件里面更改rgb的透明度来重新渲染

**Comment by CNReporter** [comment]
> > 没有生效
> 
> 需要搭配 More Materials 插件


https://github.com/user-attachments/assets/1d60a9ba-c1c7-4165-a29b-14a27fdc7126

**Comment by MUKAPP** [comment]
@Leonsama 更新到最新版 More Materials 试试呢

**Comment by CNReporter** [comment]
> @Leonsama 更新到最新版 More Materials 试试呢

基本可以使用了 只有首次登录或首次登录完切换回话透明会失效一次 去material里面切换配置重新渲染一次 本次登录透明就不会再失效了
