### ISSUE TITLE
bug 设置界面 显示出错

### ISSUE THREAD

**Issue by Keeperorowner** [MUKAPP/BetterQQNT-MSpring-Theme#92]
<img width="758" alt="屏幕截图 2024-07-18 004631" src="https://github.com/user-attachments/assets/15b456d9-f774-4576-b22e-6c6f25858f5a">

如图

**Comment by MUKAPP** [comment]
https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/releases/tag/v1.3.5
