### ISSUE TITLE
新版本qq覆盖自己气泡颜色失效

### ISSUE THREAD

**Issue by Arcticn** [MUKAPP/BetterQQNT-MSpring-Theme#93]
qqnt版本9.9.12-25765 (64位)
liteloader版本1.1.2
mspring版本1.3.4

非独立窗口时失效
在独立窗口打开消息窗口时正常显示主题色
![0c5ece3df255f32ce34c42bffeb1eb54](https://github.com/user-attachments/assets/70568406-5cd3-47fd-9941-1720d19775fe)
![QQ_1721356671407](https://github.com/user-attachments/assets/44e030f6-07a5-4dce-bad9-c5596d6de751)

**Comment by MUKAPP** [comment]
https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/releases/tag/v1.3.5
