### ISSUE TITLE
轻量工具箱开启自定义背景时 强制覆盖气泡颜色失效

### ISSUE THREAD

**Issue by immortal521** [MUKAPP/BetterQQNT-MSpring-Theme#95]
![](https://github.com/user-attachments/assets/2f3a20fe-17fd-4645-9665-716b97395e14)
![](https://github.com/user-attachments/assets/a49799e7-5a92-44c9-8759-1ed3c21e07f3)
![](https://github.com/user-attachments/assets/2b13ec9a-2c83-4b9b-9473-03c1ef2d510b)

**Comment by MUKAPP** [comment]
https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/releases/tag/v1.3.5
