### ISSUE TITLE
[BUG] 安装插件导致渲染出错

### ISSUE THREAD

**Issue by LINKlang** [MUKAPP/BetterQQNT-MSpring-Theme#96]
在更新llqqbt1.2.0，qq9.9.12_240729之后，只要加载了msping-theme这个插件就会导致qq无法正常渲染主页面（具体标签：白屏 带图），且导致整个电脑卡起来
![image](https://github.com/user-attachments/assets/f04e95d3-ac3a-4566-89e9-644a065a0bc9)

![image](https://github.com/user-attachments/assets/7ea51bfa-9f75-4941-8a45-a9fab1f3f84c)

**Comment by MUKAPP** [comment]
9.9.15 正常
![image](https://github.com/user-attachments/assets/8e3ba9af-9a3d-4a4f-b0aa-66c5ae948a3b)

**Comment by LINKlang** [comment]
刚刚发现了，只安装主题插件的时候是可以的，以下是我的插件列表，是否是有其他插件冲突了呢？
![image](https://github.com/user-attachments/assets/575e7d03-a831-4c66-89f2-f690b77641c5)

**Comment by LINKlang** [comment]
找到问题了，是llapi这个依赖的冲突问题，不知道怎么回事和这个主题插件冲突了，删除后正常
