### ISSUE TITLE
在夜间模式下无法覆盖会话列表中当前会话的颜色

### ISSUE THREAD

**Issue by amakerlife** [MUKAPP/BetterQQNT-MSpring-Theme#99]
LiteLoader 1.2.0 & QQNT 9.9.15-26740 on Windows11

期望应将选中的会话覆盖为主题色。

![image](https://github.com/user-attachments/assets/63dc2c84-3721-4328-b622-369a4265f847)

已开启 轻量工具箱、More Materials。

**Comment by oreme2** [comment]
同 9.9.15-26909 
夜间模式的界面也无法blur，是纯黑色

**Comment by KasumiNova** [comment]
+1

**Comment by MUKAPP** [comment]
https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/releases/tag/v1.3.5
